### ISSUE TITLE
"Exception java.lang.UnsatisfiedLinkError: Can't load library" on streams-data lab

### ISSUE THREAD

**Issue by brucetorres** [RedHatTraining/AD482-apps#81]
Hi,
I'm try to run the lab "streams-data", with the command: `./mvnw clean package quarkus:dev`
I'm using a MacOS Monterey with M1 chip.

The application runs up, but is rising errors related to RocksDB

The logs as follows:
[streams-data.log](https://github.com/RedHatTraining/AD482-apps/files/9126796/streams-data.log)

**Comment by stencell** [comment]
I've captured this as an issue in our course repository so we can figure out how to address it in the future. We don't currently test on any M1 devices and while we included a warning about OpenJDK in the setup, it appears there might be some issues with individual exercises or labs. 

If this is a blocker for you, which it doesn't seem to be, you can use the cloud workstation as well. 

Sorry for the inconvenience.
